// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhrPz4ATVken9jH8UbOjNEqfbYf-ofqE',
    appId: '1:28286475276:web:b3f00c2834247dcc23e229',
    messagingSenderId: '28286475276',
    projectId: 'home-security-f3878',
    authDomain: 'home-security-f3878.firebaseapp.com',
    storageBucket: 'home-security-f3878.firebasestorage.app',
    measurementId: 'G-52L4QGJDVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqiDd7unZn-PzAfDhE0Snino4UVTk9tqU',
    appId: '1:28286475276:android:b323a2454e94fabe23e229',
    messagingSenderId: '28286475276',
    projectId: 'home-security-f3878',
    storageBucket: 'home-security-f3878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5uWXgmSG_2Tuchg6LTnXA7u1ZXYKaXTc',
    appId: '1:28286475276:ios:071027225f5af2e323e229',
    messagingSenderId: '28286475276',
    projectId: 'home-security-f3878',
    storageBucket: 'home-security-f3878.firebasestorage.app',
    iosClientId: '28286475276-lem34m7ch3ai3973rm5b6b7433j5aj7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5uWXgmSG_2Tuchg6LTnXA7u1ZXYKaXTc',
    appId: '1:28286475276:ios:071027225f5af2e323e229',
    messagingSenderId: '28286475276',
    projectId: 'home-security-f3878',
    storageBucket: 'home-security-f3878.firebasestorage.app',
    iosClientId: '28286475276-lem34m7ch3ai3973rm5b6b7433j5aj7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeSecurity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzhrPz4ATVken9jH8UbOjNEqfbYf-ofqE',
    appId: '1:28286475276:web:3561d43dc3ca3f0923e229',
    messagingSenderId: '28286475276',
    projectId: 'home-security-f3878',
    authDomain: 'home-security-f3878.firebaseapp.com',
    storageBucket: 'home-security-f3878.firebasestorage.app',
    measurementId: 'G-L16ZH0KND2',
  );
}
