import queue

VIDEO_DEVICE_INDEX = 1

OUTPUT_FOLDER = "Videos"
CHUNK_DURATION = 300
CREDENTIALS_FILE = "device_credentials.json"

STREAM_WIDTH = 480
STREAM_HEIGHT = 320
STREAM_QUALITY = 50

STREAM_INTERVAL = 0.15

MQTT_BROKER = "YOUR_HIVEMQ_CLUSTER_URL"
MQTT_PORT = 8883
MQTT_USERNAME = "YOUR_MQTT_USERNAME"
MQTT_PASSWORD = "YOUR_MQTT_PASSWORD"

TOPIC_VIDEO_BASE = "home/security/video"

GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
AI_CHECK_INTERVAL = 5

FIREBASE_CREDENTIALS_FILE = "YOUR_FIREBASE_ADMINSDK_FILE.json"
TARGET_USER_ID = "YOUR_FIREBASE_USER_UID"

CLOUDINARY_CLOUD_NAME = "YOUR_CLOUDINARY_CLOUD_NAME"
CLOUDINARY_API_KEY = "YOUR_CLOUDINARY_API_KEY"
CLOUDINARY_API_SECRET = "YOUR_CLOUDINARY_API_SECRET"

video_stream_queue = queue.Queue(maxsize=1)